[package]
name = "zeiss_control"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
serialport = "4.2.2"
nokhwa = { version = "0.10.4", features = ["input-native", "output-wgpu"]}
